services:
  mongodb:
    container_name: retail_mongo
    image: mongo:8.0-noble
    ports:
      - "3005:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: evans
      MONGO_INITDB_ROOT_PASSWORD: evans
    volumes:
      - crypto-data:/data/db
    networks:
      - crypto-network

volumes:
  crypto-data: {}

networks:
  crypto-network: