services:
  mongodb:
    container_name: retail_mongo
    image: mongo:8.0-noble
    ports:
      - "3005:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: evans
      MONGO_INITDB_ROOT_PASSWORD: evans
    volumes:
      - crypto-data:/data/db
    networks:
      - crypto-network
  
  backend:
    container_name: retail_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - crypto-network
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_URI: mongodb://evans:evans@mongodb:27017/crypto?authSource=admin
  
  frontend:
    container_name: retail_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - crypto-network
    environment:
      BASE_URL: http://backend:3000

volumes:
  crypto-data: {}

networks:
  crypto-network: